### ISSUE TITLE
Does not work on Firefox.

### ISSUE THREAD

**Issue by Elaws** [zeraye/chess-analysis-firefox-extension#12]
Clicking on extension icon (in the URL bar), a "Analyzing game" message appears in the center of the screen for a good 20 seconds then either : nothing happens, or a lichess webpage appears where analysis loads for another 15 seconds.

**Comment by zeraye** [comment]
@Elaws Can you give link to the game that isn't loading?

**Comment by mgstreak** [comment]
I'm seeing the same thing on Firefox 127.0.2

Here's a link to a game that won't work: https://www.chess.com/analysis/game/live/114442250049?tab=analysis&move=68

**Comment by zeraye** [comment]
There are 2 problems:
1. Addon try to find your game from chess.com api without any timeout. So it will check your **every** chess.com game [1]. I need to add some timeout (eg. 5 seconds) and after that game PGN will be extracted manually.
2. Addon only check for matching url eg. https://www.chess.com/game/live/114442250049. If you analyse game from some other url like https://www.chess.com/analysis/game/live/114442250049 addon will try to find this game, fail (it takes long because of this I wrote at 1.) and do it manually. I have to extract game id from url, and match by id (not by url).

[1] You can't get game PGN with game id with one request. You have to manually iterate over all user's games.

I will try to fix this as fast as possbile. I hope this week 😄.

I you want to contribute, go ahead, create PR with the fix. Every support is encouraged

**Comment by Elaws** [comment]
@zeraye : Thanks for your reply ! 

Did you follow these guidelines : https://www.chess.com/clubs/forum/view/guide-unofficial-api-documentation ?

Apparently, with this method we can search only games within the same month, which would surely reduce the clutter compared with searching through all the games.

I'm curious why chess.com API doesn't allow to get PGN from a given game ID, which is a trivial request. Their API does not seem to be regularly updated anymore.

**Comment by zeraye** [comment]
I'm searching games using endpoint https://api.chess.com/pub/player/vuvuvuvuvuvu/games/archives, starting with the newest games. If player played game in the current month, this month will be researched first.

You can see that here:
https://github.com/zeraye/chess-analysis-firefox-extension/blob/760e8ebbec61bfba222fb48f28530786b4eb9fb8/src/js/background.js#L49-L62

I think chess.com doesn't allow direct fetch for PGN to reduce cheaters? But it's still super easy to get game PGN (like I do in this addon) or just scrape it from DOM

**Comment by zeraye** [comment]
Issue should be fixed by: https://github.com/zeraye/chess-analysis-firefox-extension/pull/13

**Comment by zeraye** [comment]
PR #13 merged, closing issue
